# Generated by Django 3.1 on 2020-08-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64)),
                ('accountId', models.CharField(max_length=57)),
                ('puuid', models.CharField(max_length=79)),
                ('name', models.CharField(max_length=30)),
                ('profileIconId', models.CharField(max_length=30)),
                ('summonerLevel', models.IntegerField()),
            ],
        ),
    ]
