# Generated by Django 3.1 on 2020-08-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_userinfo_revisiondate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformId', models.CharField(max_length=10)),
                ('gameId', models.IntegerField(default=0)),
                ('champion', models.IntegerField(default=0)),
                ('queue', models.IntegerField(default=0)),
                ('seaon', models.IntegerField(default=1)),
                ('timestamp', models.IntegerField(default=0)),
                ('role', models.CharField(max_length=15)),
                ('lane', models.CharField(max_length=10)),
                ('accountId', models.CharField(max_length=57)),
            ],
        ),
    ]
